### ISSUE TITLE
gh cliの説明拡充

### ISSUE THREAD

**Issue by Bucchiman** [Bucchiman/onelines#72]
# モチベーション
gh cliの説明が少ない。使いづらい。
使っているコマンドが限定されているため、コマンドを増やす必要あり。

# toDo
- [x] gh issue
    - [x] -r, --reason
    - [x] comment (2023-09-04 10:45:03)
    - [x] close   (2023-09-12 10:36:44)
    - [x] create
    - [x] delete
    - [x] edit    (2023-09-13 00:58:13)
    - [x] develop (2023-09-13 11:41:44)
    - [x] list
    - [x] lock
    - [x] pin
    - [x] reopen
    - [x] transfer
    - [x] unlock
    - [x] unpin

- [x] gh label
    - [x] clone
    - [x] create
    - [x] delete
    - [x] edit
    - [x] list

- [x] gh pr
    - [x] create
    - [x] list
    - [x] status  (2023-09-13 10:45:45)
    - [x] checkout
    - [x] checks
    - [x] close   (2023-09-13 10:55:59)
    - [x] comment (2023-09-04 10:45:03)
    - [x] diff
    - [x] edit
    - [x] lock
    - [x] merge
    - [x] ready
    - [x] review
    - [x] unlock
    - [x] view

- [x] gh project
    - [x] close
    - [x] copy
    - [x] create
    - [x] delete
    - [x] edit
    - [x] field-create
    - [x] field-delete
    - [x] field-list
    - [x] item-add
    - [x] item-archive
    - [x] item-create
    - [x] item-delete
    - [x] item-edit
    - [x] item-list
    - [x] list
    - [x] view

- [] gh alias
    - [x] delete
    - [x] import
    - [x] list
    - [] set

- [] gh codespace
    - [x] code
    - [x] cp
    - [x] create
    - [x] delete
    - [x] edit
    - [x] jupyter
    - [x] list
    - [x] logs
    - [x] ports
    - [] ports forward
    - [] ports visibility
    - [x] rebuild
    - [x] ssh
    - [x] stop
    - [x] view

- [x] gh config
    - [x] clear-cache
    - [x] get
    - [x] list
    - [x] set

- [] gh gist
    - [] clone
    - [x] create
    - [] delete
    - [x] edit
    - [x] list
    - [] rename
    - [] view

- [] gh repo
    - [x] archive
    - [x] clone
    - [x] create
    - [x] delete
    - [x] deploy-key add
    - [x] deploy-key delete
    - [x] deploy-key list
    - [x] edit
    - [x] fork
    - [x] list
    - [x] rename
    - [] set-default
    - [] sync
    - [x] unarchive
    - [] view

- [x] gh run
    - [x] cancel
    - [x] delete
    - [x] download
    - [x] list
    - [x] return
    - [x] view
    - [x] watch

- [x] gh workflow
    - [x] gh workflow disable
    - [x] gh workflow enable
    - [x] gh workflow list
    - [x] gh workflow run
    - [x] gh workflow view

**Comment by Bucchiman** [comment]
- `gh issue comment`コマンドを追加

**Comment by Bucchiman** [comment]
# 以下のコマンドを追加
- `gh workflow`
- `gh run`

**Comment by Bucchiman** [comment]
一通りコマンドを追加したので、close
