### ISSUE TITLE
Rustコマンド導入

### ISSUE THREAD

**Issue by Bucchiman** [Bucchiman/onelines#86]
# モチベーション
便利なコマンドがたくさんあることを発見したから

# Reference

# toDo
- [x] bat
- [] repgrep, ripgrep-all
- [x] fd, fselect
- [] starship
- [x] exa, lsd, nat
- [x] nushell
- [x] navi, tealdeer
- [x] delta
- [x] hyperfine
- [x] xsv, csview
- [x] py-spy
- [x] bandwhich, gping, ht, dog
- [x] hexyl, bingrep
- [x] broot
- [x] tokei
- [x] genact, globe, glitchcat
- [] monolith
- [] shellharden
- [] fnm, volta
- [x] pastel
- [x] gitui
- [x] onefetch
- [] git-interactive-rebase-tool
- [] skim
- [x] watchexec
- [x] dust, diskonaut, dua-cli, dutree
- [x] zoxide
- [] ytop, bottom, zenith
- [] mcfly
- [x] sd, desed
- [x] topgrade
- [x] pueue
- [x] procs
- [x] grex
- [x] silicon
- [x] angle-grinder
- [] drill, oha
- [] choose
- [] tmux-thumbs
